########## Testcase 0: Failed ##########
Expected Output: 
76.8
6

Your Output: 
76.8
6
6
Traceback (most recent call last):
  File "Deep_List.py", line 77, in <module>
    main()
  File "Deep_List.py", line 66, in main
    getDeep(data)
  File "Deep_List.py", line 58, in getDeep
    print(data)
NameError: name 'data' is not defined
----------------------------------------

########## Testcase 1: Failed ##########
Expected Output: 
5.5
1

Your Output: 
5.5
1
1
Traceback (most recent call last):
  File "Deep_List.py", line 77, in <module>
    main()
  File "Deep_List.py", line 66, in main
    getDeep(data)
  File "Deep_List.py", line 58, in getDeep
    print(data)
NameError: name 'data' is not defined
----------------------------------------

########## Testcase 2: Failed ##########
Expected Output: 
1
6

Your Output: 
1
6
6
Traceback (most recent call last):
  File "Deep_List.py", line 77, in <module>
    main()
  File "Deep_List.py", line 66, in main
    getDeep(data)
  File "Deep_List.py", line 58, in getDeep
    print(data)
NameError: name 'data' is not defined
----------------------------------------

########## Testcase 3: Failed ##########
Expected Output: 
5
4

Your Output: 
5
4
4
Traceback (most recent call last):
  File "Deep_List.py", line 77, in <module>
    main()
  File "Deep_List.py", line 66, in main
    getDeep(data)
  File "Deep_List.py", line 58, in getDeep
    print(data)
NameError: name 'data' is not defined
----------------------------------------

########## Testcase 4: Failed ##########
Expected Output: 
0
8

Your Output: 
0
8
8
Traceback (most recent call last):
  File "Deep_List.py", line 77, in <module>
    main()
  File "Deep_List.py", line 66, in main
    getDeep(data)
  File "Deep_List.py", line 58, in getDeep
    print(data)
NameError: name 'data' is not defined
----------------------------------------

########## Testcase 5: Failed ##########
Expected Output: 
5654134.9
10

Your Output: 
5654134.9
10
10
Traceback (most recent call last):
  File "Deep_List.py", line 77, in <module>
    main()
  File "Deep_List.py", line 66, in main
    getDeep(data)
  File "Deep_List.py", line 58, in getDeep
    print(data)
NameError: name 'data' is not defined
----------------------------------------

